spring:
  application:
    name: eBanca
  datasource:
    url: jdbc:mysql://localhost:3306/merch?createDatabaseIfNotExist=true
    username: root
    password: 1qaz!QAZ

    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  servlet:
    multipart:
      max-file-size: 16MB
      max-request-size: 16MB
      enabled: true

server:
  port: 8080

storage:
  location: '/home/administrator/'




